#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_COMPONENTS := camara_comp
SIMICS_API := latest
THREAD_SAFE:=yes
PYTHON_FILES = camara_comp.py module_load.py

include $(MODULE_MAKEFILE)
